language: ruby

dist: trusty

addons:
  postgresql: "9.6"

services:
  - postgresql

cache:
  bundler: true

rvm:
  - 2.4.2

jobs:
  include:
    - stage: code quality
      script: bundle exec rubocop

    - stage: unit test
      before_script:
        - cp .env.ci .env
        - bundle exec rake db:create
        - bundle exec rake db:migrate
