version: "2"

services:
  db:
    image: postgres:10.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  api_doc:
    image: 'bukalapak/snowboard'
    command: html -o index.html -b 0.0.0.0:8088 -s /api/api.apib
    ports:
      - "8088:8088"
    volumes:
      - ./api.apib:/api/api.apib

volumes:
  pg_data:
